<form id="registrationForm" enctype="multipart/form-data" method="post" action="">
<fieldset>
<span id="error">&nbsp;</span><br />
<input type="hidden" name="MAX_FILE_SIZE" value="512000" />
<div><label for="username">User Name </label><input type="text" name="username" id="username"></div>
<div><label for="password">Password</label><input type="password" name="password" id="password"></div>
<div><label for="repeatpassword">Repeat Password</label><input type="password" name="repeatpassword" id="repeatpassword"></div>
<div><label for="firstname">First Name </label><input type="text" name="firstname" id="firstname"></div>
<div><label for="lastname">Last Name </label><input type="text" name="lastname" id="lastname"></div>
<div><label for="email">Email Address </label><input type="email" name="email" id="email"></div>
<div><label for="phone">Phone Number</label><input type="tel" name="phone" id="phone"></div>
<div><label for="avatar">Avatar Image </label><input type="file" name="avatar" id="avatar"></div>
<div><input type="submit" value="Submit" id="submit"></div>
</fieldset>
</form><br/>